version = 0.1

[default.deploy.parameters]
stack_name = "rikitrakilambda"
s3_bucket = "rikitraki-sam-artifacts" 
s3_prefix = "rikitrakilambda"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-west-2"